### ISSUE TITLE
SSZ no longer available on Appspot

### ISSUE THREAD

**Issue by StenCalDabran** [BSData/space-station-zero#12]
**Describe the bug**
Space Station Zero is not in the List, neither in the App nor on their [Data Files site](https://battlescribedata.appspot.com/#/repos)

**To Reproduce**
Just look on repository list on  [BattleScribe Data Files](https://battlescribedata.appspot.com/#/repos)

**Expected behavior**
SSZ data being available in BattleScribe

**Device and data (please complete the following information):**
 - OS: Android 13
 - BattleScribe version [e.g. 2.03.25.338] (should be newest, I installed it from Google Play Store today)
 - Release version all

**Additional context**
According to a friend it was available a few weeks ago but is no longer available for them as well.

**Comment by cartag** [comment]
It's an issue with AppSpot itself. There's a post on the 40k BSData repo with more information: https://github.com/BSData/wh40k/issues/1706

The Gallery method will be a workaround to where it will never be an issue. Feel fortunate you're on Android, appdev never set up the functionality correctly on iOS.
