### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by oggurt-da-bog-zombie** [BSData/space-station-zero#3]
### Reference contact

@car_tag

### Your Discord

oggurt_da_bog_zombie

### Additional information

Would like to help with the SSZ repo, have a few fixes ready to share.

**Comment by Mad-Spy** [comment]
@cartag if you comment with slash invite, it'll add @oggurt-da-bog-zombie to the repo,

**Comment by cartag** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/2995832543)
:robot: Invited @oggurt-da-bog-zombie with **push** access. Invite can be accepted on https://github.com/BSData/space-station-zero/invitations
