### ISSUE TITLE
[Anon] Bug report: Space Station Zero.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/space-station-zero#5]
**File:** Space Station Zero.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Advanced Technology is not available for all commanders even though the rules on page 32 states a commander can take one additional piece of gear from what their ship is allowed OR one piece of Advanced Technology.

**Comment by cartag** [comment]
Resolved in next release
